### ISSUE TITLE
Data plot displays incorrect version from cache

### ISSUE THREAD

**Issue by camargoproject** [PublicNTP/globalprobe-ui#3]
*GPv01-001*: click-only navigation

_How to reproduce_:

• Start at dashboard (http://pntp-gp-ui-20190219082147-hostingbucket-dev.s3-website.us-east-2.amazonaws.com/)
• Click *Server Details* for any server (e.g, `stratum2-01.bom02.publicntp.org`)
• All fields will populate properly
• Click *Dashboard*
• Click *Server Details* for any other server (e.g., `stratum2-01.gru01.publicntp.org`)
• *Server URL* field is properly populated, but *Name* and *Server IP Addresses* are set to the "old" values for `stratum2-01.bom02.publicntp.org`)
• Force-reload (Ctrl-shift-R) causes all values to update appropriately

_Desired behavior_:

Upon clicking details for second server, all values should reflect proper settings for server you clicked details on.

**Comment by bryan-wilson** [comment]
Diagnosed: The issue is the server history component's "caching key" was the same name for all server history pages.  The quick fix is to simply remove the keep-alive tag wrapping the router component instance.  The longer term fix is to create an explicit graph component separate from the history page, and then cache that by a name unique to the data set.
